#!/usr/bin/expect -f 
#exp_internal 1
#package require cmdline
proc usage {} {
  puts "Usage: [info script] <host1> <host2> <hostn>"
  exit 1
}

set totalargs [llength $argv]
if { $totalargs == 0 } {
	usage
}

 # get password for ilo 
stty -echo
send_user "Please enter root ilo password : "
expect_user -re "(.*)\n"
set root_pass $expect_out(1,string)
send_user "\n"
stty echo

# ntp host
ntp_host1=10.10.4.12
ntp_host2=10.10.4.13

# parse command line arguments. 

set timeout -1
set hosts [concat $argv ]
foreach host $hosts {
	set timeout 10
	
	# login
	spawn ssh -o StrictHostKeyChecking=no root@$host
	match_max 100000
	expect "*?ord:"
	sleep 3
	send -- "$root_pass\r"
	expect "*->"
	sleep 1

	# set ntp 
	send -- "set /SP/clients/ntp/server/1 address=10.234.4.12\r"
	send -- "set /SP/clients/ntp/server/2 address=10.234.4.13\r"
	sleep 1
	send -- "set /SP/clock usentpserver=enabled\r"
	
	send -- "show /SP/clock\r"
	
	send -- "exit\r"
	expect eof
}
